sudo: enabled
os: osx
language: node_js
node_js:
- '9'
notifications:
  slack:
    secure: Aq2ZMQB8AaSQhPx94otWGYbDP9FuhU517DLETemZ+AqfU+dEI7H6GzrB9+nLGnUZ2z0RukA2RSiJQmL/PoL3c04MlLSx7GGF+t0ceoHmGWnYEzoTlwX5VAkg+K5PshGhRTQbZ6/fzVPn3eipOM7hEidER5OShVQ4BzvQvXTL505UG1LC6MKUGNjt2Ft1pb8A45mVpgT4ijtJ73lkJg91+Hp5ZVt3uCGF6qYZQhTkb0EdR7TRiEJlAOXWeRt9bbvIaZ1/27fhmNz+qoBeq5DaQsrxEcDDWTYT+KyJwHc7g1RwjDD6WTi+sX5q5v0h9DhIF8jw/4BUeHrUBYrtwMS4lErsFV98cf8XAuKOY+EDAKzitYdgYzuNQr/ojLkY7aaPWXta0EQqnG5duBX8LZfDfnxfva/IGBK1FHV5mSVYsGBnLE21q0/2wWOPPlWClqQz0U7vI8Q65fF/LARCRokM+VHQ5WVXcca13SwYlSnF64QIfq0WSu4hufyd+v52dEvSTjtQeVLb4L8JLpP3e7iOOxfuQXXNASHKqXy9bsfReGir/7hZQuU8RTjNomiwDwuBAzN/ma1JgZx7UnD271sJwsChtJkZmPQYvIs37ybQPg5/iTnLmSd4n1aGOBBh3E7NCfBacKFrlSg1wRwjLOu5WbRbRZ8ClYOI//swNTN1Nw4=
